// WebP-first <picture> wrapper: intentionally raw <img>, assets pre-optimized
// via scripts/optimize-images.mjs (eslint no-img-element does not apply).
import type { ImgHTMLAttributes } from "react";

type SmartImageProps = ImgHTMLAttributes<HTMLImageElement> & {
  src: string;
  alt: string;
  /** Above-the-fold LCP image: eager load, high fetch priority, sync decode. */
  priority?: boolean;
};

/* Assets with no WebP sibling (sprites/cursor must stay lossless-sharp,
   map JPGs whose WebP came out larger than the source). */
const NO_WEBP = /(\/cursor\.png$|-sprite\.jpg$|\/orsterra(-768)?\.jpg$)/;

function webpSrc(src: string): string | null {
  if (!src.startsWith("/")) return null;
  if (NO_WEBP.test(src)) return null;
  const dot = src.lastIndexOf(".");
  return dot < 0 ? null : `${src.slice(0, dot)}.webp`;
}

/**
 * WebP-first image with JPG/PNG fallback. WebP siblings are generated by
 * `node scripts/optimize-images.mjs`. Lazy + async decode by default so
 * below-fold images never block the main thread or LCP.
 */
export function SmartImage({ src, alt, priority = false, ...rest }: SmartImageProps) {
  const webp = webpSrc(src);
  const img = (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={alt}
      loading={priority ? "eager" : (rest.loading ?? "lazy")}
      decoding={priority ? "sync" : "async"}
      {...(priority ? { fetchPriority: "high" as const } : {})}
      {...rest}
    />
  );
  if (!webp) return img;
  // display:contents keeps <img> sized as if <picture> were not there.
  return (
    <picture className="contents">
      <source srcSet={webp} type="image/webp" {...(rest.sizes ? { sizes: rest.sizes } : {})} />
      {img}
    </picture>
  );
}

